source 'https://rubygems.org'

ruby '2.1.3'
gem 'rails', '4.1.12'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'
gem 'devise', '3.3.0'
gem 'rack-cors', :require => 'rack/cors'
gem 'active_model_serializers', '~> 0.10.0'
gem 'doorkeeper'
gem 'devise-doorkeeper'

group :test, :development do
   gem 'byebug'
   gem "rspec"
   gem "rspec-rails", "~> 2.0"
   gem 'factory_girl'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
